/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Actividad;
import Model.Docente;
import Model.Materia;
import Model.Periodo;
import gb090091_hs110065.ActividadesTableModel;
import gb090091_hs110065.conexion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SISTOP
 */
public class Actividades extends javax.swing.JInternalFrame {
    Docente _gDocente;
    List<Materia> _gMaterias;
    List<Periodo> _gPeriodos;
    int _gidMateriaSeleccionada;
    int _gidPeriodoSeleccionado;
    ActividadesTableModel SourceActividades;
    /**
     * Creates new form Actividades
     */
    public Actividades(Docente _gDocente) {
        initComponents();
        this._gDocente = _gDocente;
        this.jbcMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(this.getMaterias()));
        this.jbcPeriodo1.setEnabled(false);
        this.jbtnagregar.setEnabled(false);
        this.jTableActividades.setModel(SourceActividades = new ActividadesTableModel() );
    }
    
    public String[] getMaterias() {
        conexion con = new conexion();
        _gMaterias = con.getListaMateriasDocente(_gDocente.getIdDocente());
        String[] Result = new String[_gMaterias.size() + 1];
        Result[0] = "Seleccione";
        for (int i = 1; i < _gMaterias.size() + 1; i++) {
            Result[i] = _gMaterias.get(i - 1).getNombre();
        }
        return Result;
    }
    
    public String[] getPeriodos() {
        if (jbcMateria1.getSelectedIndex() != 0) {
            jbtnagregar.setEnabled(false);
            _gidMateriaSeleccionada = _gMaterias.stream().filter(par -> par.getNombre().equals(jbcMateria1.getSelectedItem())).findFirst().get().getIdMateria();
            jbcPeriodo1.setEnabled(true);
            conexion con = new conexion();
            _gPeriodos = con.getListaPeriodoMateriasDocente(_gDocente.getIdDocente(), _gidMateriaSeleccionada);
            if (_gPeriodos != null) {
                String[] Result = new String[_gPeriodos.size() + 1];
                Result[0] = "Seleccione";
                for (int i = 1; i < _gPeriodos.size() + 1; i++) {
                    Result[i] = ((Integer) _gPeriodos.get(i - 1).getNumPeriodo()).toString();
                }
                return Result;
            }
        }
        jbcPeriodo1.setEnabled(false);
        return new String[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbcMateria1 = new javax.swing.JComboBox<>();
        jbcPeriodo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        jbtnagregar = new javax.swing.JButton();

        jbcMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbcMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcMateria1ActionPerformed(evt);
            }
        });

        jbcPeriodo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Materia");

        jLabel2.setText("Periodo");

        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableActividades);

        jbtnagregar.setText("Agregar Actividad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jbcMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbcPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jbtnagregar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbcMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jbcPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtnagregar)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcMateria1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableActividades;
    private javax.swing.JComboBox<String> jbcMateria1;
    private javax.swing.JComboBox<String> jbcPeriodo1;
    private javax.swing.JButton jbtnagregar;
    // End of variables declaration//GEN-END:variables
}
