/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Actividad;
import Model.Docente;
import Model.Materia;
import Model.Periodo;
import gb090091_hs110065.conexion;
import java.util.List;

/**
 *
 * @author eleme
 */
public class RegistroNotas extends javax.swing.JInternalFrame {

    Docente _gDocente;
    List<Materia> _gMaterias;
    List<Periodo> _gPeriodos;
    List<Actividad> _gActividades;
    int _gidMateriaSeleccionada;
    int _gidPeriodoSeleccionado;
    int _gidActividadSeleccionada;

    /**
     * Creates new form RegistroNotas
     */
    public RegistroNotas(Docente _gDocente) {
        initComponents();
        this._gDocente = _gDocente;
        this.jcbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(this.getMaterias()));
        this.jcbPeriodo.setEnabled(false);
        this.jcbActividad.setEnabled(false);
        //this.jcbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(this.getActividades()));
    }

    public String[] getMaterias() {
        conexion con = new conexion();
        _gMaterias = con.getListaMateriasDocente(_gDocente.getIdDocente());
        String[] Result = new String[_gMaterias.size() + 1];
        Result[0] = "Seleccione";
        for (int i = 1; i < _gMaterias.size() + 1; i++) {
            Result[i] = _gMaterias.get(i - 1).getNombre();
        }
        return Result;
    }

    public String[] getPeriodos() {
        if (jcbMateria.getSelectedIndex() != 0) {
            jcbActividad.setEnabled(false);
            jcbActividad.removeAllItems();
            _gidMateriaSeleccionada = _gMaterias.stream().filter(par -> par.getNombre().equals(jcbMateria.getSelectedItem())).findFirst().get().getIdMateria();
            jcbPeriodo.setEnabled(true);
            conexion con = new conexion();
            _gPeriodos = con.getListaPeriodoMateriasDocente(_gDocente.getIdDocente(), _gidMateriaSeleccionada);
            if (_gPeriodos != null) {
                String[] Result = new String[_gPeriodos.size() + 1];
                Result[0] = "Seleccione";
                for (int i = 1; i < _gPeriodos.size() + 1; i++) {
                    Result[i] = ((Integer) _gPeriodos.get(i - 1).getNumPeriodo()).toString();
                }
                return Result;
            }            
        }
        jcbPeriodo.setEnabled(false);
        return new String[0];
    }

    public String[] getActividades() {
        if (jcbPeriodo.getSelectedIndex() != 0) {
            _gidPeriodoSeleccionado = _gPeriodos.stream().filter(par -> par.getNumPeriodo() == Integer.parseInt(jcbPeriodo.getSelectedItem().toString())).findFirst().get().getIdPeriodo();

            jcbActividad.setEnabled(true);
            conexion con = new conexion();
            _gActividades = con.getListaActividadPeriodoMateriasDocente(_gDocente.getIdDocente(), _gidPeriodoSeleccionado, _gidMateriaSeleccionada);
            if (_gActividades != null) {
                String[] Result = new String[_gActividades.size() + 1];
                Result[0] = "Seleccione";
                for (int i = 1; i < _gActividades.size() + 1; i++) {
                    Result[i] = _gActividades.get(i - 1).getNombre();
                }
                return Result;
            }

        }
        jcbActividad.setEnabled(false);
        return new String[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbMateria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbPeriodo = new javax.swing.JComboBox<>();
        jcbActividad = new javax.swing.JComboBox<>();
        jbtnProcesar = new javax.swing.JButton();

        jcbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Materia");

        jLabel2.setText("Periodo");

        jLabel3.setText("Actividad");

        jcbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPeriodoActionPerformed(evt);
            }
        });

        jcbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActividadActionPerformed(evt);
            }
        });

        jbtnProcesar.setText("Procesar");
        jbtnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnProcesar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jcbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbtnProcesar))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateriaActionPerformed
        this.jcbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(this.getPeriodos()));
    }//GEN-LAST:event_jcbMateriaActionPerformed

    private void jcbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPeriodoActionPerformed
        this.jcbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(this.getActividades()));
    }//GEN-LAST:event_jcbPeriodoActionPerformed

    private void jbtnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcesarActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jbtnProcesarActionPerformed

    private void jcbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActividadActionPerformed
        if (jcbActividad.getSelectedIndex() != 0) {
            _gidActividadSeleccionada = _gActividades.stream().filter(o -> o.getNombre().equals(jcbActividad.getSelectedItem().toString())).findFirst().get().getIdActividades();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnProcesar;
    private javax.swing.JComboBox<String> jcbActividad;
    private javax.swing.JComboBox<String> jcbMateria;
    private javax.swing.JComboBox<String> jcbPeriodo;
    // End of variables declaration//GEN-END:variables
}
